name: pytorch_sac
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - dm_control
  - pip:
    - termcolor
    - git+https://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch
