defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e4
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 50

eval_frequency: 100
num_eval_episodes: 10

device: cpu

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true


seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
